apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: default
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: epitechcontent/t-dop-600-worker:k8s
          resources:
            limits:
              memory: "256M"
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-redis
                  key: REDIS_HOST
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-postgres
                  key: database_host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap-postgres
                  key: database_port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap-postgres
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secrets-username
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: password