api:
  dashboard: true
  insecure: true

providers:
  kubernetesCRD:
    namespaces:
      - kube-public
      - traefik
  kubernetesIngress:
    namespaces:
      - default
      - traefik

service:
  exposedPorts:
    traefik:
      exposed: true

ports:
  traefik:
    expose:
      default: true
    port: 9000
    targetPort: 9000
  web:
    port: 80
    targetPort: 8000
  websecure:
    port: 443
    targetPort: 8443

ingressClass:
  enabled: false
